version: '3.1'

services:
  db:
    container_name: inter-week-backend
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dio-inter
      POSTGRES_DB: inter
